# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae01782972ba3e411ba37a01f642d3a04b6f5a00246e8513b9cfcdc739452f18ed124488ad2a44301f12a927b0b3d636fd158a1d12b4e3fb5d728859c5c7699c

test:
  secret_key_base: 6332d19189315b5fe844335147db714d4664a68c1deca9ef46b0fc6ff1e7c1b29bfa21280f4bafd1adc0d4652be99d3e4b302f66c93097b0290a48a2c01efa7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
